default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= puts "DB_USERNAME: #{ENV['DB_USERNAME']}"; ENV['DB_USERNAME'] %>
  password: <%= puts "DB_PASSWORD: #{ENV['DB_PASSWORD']}"; ENV['DB_PASSWORD'] %>
  host: <%= puts "DB_HOST: #{ENV['DB_HOST']}"; ENV['DB_HOST'] %>
  database: <%= puts "DB_NAME: #{ENV['DB_NAME']}"; ENV['DB_NAME'] %>
  ssl_mode: :required
  port: 3306

  # sslca: "config/aws-rds-ca-2019-root.pem"
  # sslverify: true

development:
  <<: *default
  database: your_app_name_development

test:
  <<: *default
  database: your_app_name_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>