default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: 127.0.0.1
  port: 3307 # This MUST match the local_port in the initializer
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  ssl_mode: :required
  enable_cleartext_plugin: true # <-- ADD THIS LINE


development:
  <<: *default
  database: <%= ENV['DB_NAME'] %> # <-- Change this line

test:
  <<: *default
  database: your_app_name_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  # In production, you'll likely connect directly without a bastion,
  # so you would override host and remove the port here.
  host: <%= ENV['DB_HOST'] %>
  port: 3306