source 'https://rubygems.org'
git_source(:github) { |repo_name| "https://github.com/#{repo_name}.git" }

ruby '3.3.4'

gem 'rails', '~> 7.0.4'
gem 'mysql2', '>= 0.5'
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'concurrent-ruby', '1.3.4'
gem 'bootsnap', require: false
gem 'sprockets-rails' # Add this line
gem 'dotenv-rails', groups: [:development, :test]
